sudo: required
services:
  - docker

before_install:
  - docker build -t louis/cicd-toy -f Dockerfile.dev .

script:
  - docker run -e CI=true louis/cicd-toy npm run test

deploy:
  provider: elasticbeanstalk
  region: "ap-southeast-1"
  app: "cicd-toy"
  env: "CicdToy-env"
  bucket_name: "elasticbeanstalk-ap-southeast-1-676572914062"
  bucket_path: "cicd-toy"
  on:
    branch: master
  access_key_id:
    secure: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"